// CodeGear C++Builder
// Copyright (c) 1995, 2025 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'GXScene_Physics_RT.dpk' rev: 36.00 (Windows)

#ifndef GXScene_Physics_RTHPP
#define GXScene_Physics_RTHPP

#pragma delphiheader begin
#pragma option push
#if defined(__BORLANDC__) && !defined(__clang__)
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#endif
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <GXS.NGDManager.hpp>
#include <GXS.NGDRagdoll.hpp>
#include <GXS.ODEManager.hpp>
#include <GXS.ODERagdoll.hpp>
#include <GXS.ODESkeletonColliders.hpp>
#include <GXS.ODEUtils.hpp>
#include <GXS.PhysFields.hpp>
#include <GXS.PhysForces.hpp>
#include <GXS.PhysInertias.hpp>
#include <GXS.PhysJoints.hpp>
#include <GXS.PhysManager.hpp>
#include <ModuleLoader.hpp>	// (<weak>)
#include <Newton.Import.hpp>
#include <NGD.Import.hpp>
#include <ODE.Import.hpp>
#include <System.Types.hpp>	// (rtl)
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.PkgHelper.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.Messages.hpp>	// (rtl)
#include <System.SysConst.hpp>	// (rtl)
#include <Winapi.ImageHlp.hpp>	// (rtl)
#include <Winapi.SHFolder.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.RTLConsts.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <Winapi.ActiveX.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Hash.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Generics.Collections.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Diagnostics.hpp>	// (rtl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <Stage.VectorTypes.hpp>	// (GXScene_RT)
#include <Stage.VectorGeometry.hpp>	// (GXScene_RT)
#include <Stage.Manager.hpp>	// (GXScene_RT)
#include <Stage.Strings.hpp>	// (GXScene_RT)
#include <GXS.PersistentClasses.hpp>	// (GXScene_RT)
#include <GXS.VectorLists.hpp>	// (GXScene_RT)
#include <GXS.XCollection.hpp>	// (GXScene_RT)
#include <GXS.GeometryBB.hpp>	// (GXScene_RT)
#include <GXS.BaseClasses.hpp>	// (GXScene_RT)
#include <Winapi.OpenGL.PkgHelper.hpp>	// (rtl)
#include <Winapi.OpenGL.hpp>	// (rtl)
#include <Winapi.OpenGLext.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Math.Vectors.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <System.ImageList.hpp>	// (rtl)
#include <FMX.Consts.hpp>	// (fmx)
#include <System.Win.Devices.hpp>	// (rtl)
#include <System.Devices.hpp>	// (rtl)
#include <System.Analytics.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <FMX.BehaviorManager.hpp>	// (fmx)
#include <FMX.Styles.hpp>	// (fmx)
#include <FMX.VirtualKeyboard.hpp>	// (fmx)
#include <System.StrUtils.hpp>	// (rtl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Win.Crtl.hpp>	// (rtl)
#include <System.RegularExpressionsAPI.hpp>	// (rtl)
#include <System.RegularExpressionsConsts.hpp>	// (rtl)
#include <System.RegularExpressionsCore.hpp>	// (rtl)
#include <System.RegularExpressions.hpp>	// (rtl)
#include <FMX.Utils.hpp>	// (fmx)
#include <FMX.Text.hpp>	// (fmx)
#include <FMX.TextLayout.hpp>	// (fmx)
#include <FMX.Materials.hpp>	// (fmx)
#include <FMX.Surfaces.hpp>	// (fmx)
#include <FMX.Types3D.hpp>	// (fmx)
#include <FMX.Filter.hpp>	// (fmx)
#include <FMX.Filter.Custom.hpp>	// (fmx)
#include <FMX.Effects.hpp>	// (fmx)
#include <FMX.MultiResBitmap.hpp>	// (fmx)
#include <FMX.Ani.hpp>	// (fmx)
#include <FMX.AcceleratorKey.hpp>	// (fmx)
#include <Winapi.CommCtrl.hpp>	// (rtl)
#include <Winapi.Qos.hpp>	// (rtl)
#include <Winapi.Winsock2.hpp>	// (rtl)
#include <Winapi.IpExport.hpp>	// (rtl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Winapi.RegStr.hpp>	// (rtl)
#include <Winapi.WinInet.hpp>	// (rtl)
#include <Winapi.UrlMon.hpp>	// (rtl)
#include <Winapi.ObjectArray.hpp>	// (rtl)
#include <Winapi.StructuredQueryCondition.hpp>	// (rtl)
#include <Winapi.PropSys.hpp>	// (rtl)
#include <Winapi.MSXMLIntf.hpp>	// (rtl)
#include <Winapi.ShlObj.hpp>	// (rtl)
#include <Winapi.KnownFolders.hpp>	// (rtl)
#include <System.Masks.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <FMX.ImgList.hpp>	// (fmx)
#include <Winapi.DxgiFormat.hpp>	// (rtl)
#include <Winapi.Wincodec.hpp>	// (rtl)
#include <Winapi.MultiMon.hpp>	// (rtl)
#include <Winapi.DXTypes.hpp>	// (rtl)
#include <Winapi.DxgiType.hpp>	// (rtl)
#include <Winapi.DXGI.hpp>	// (rtl)
#include <Winapi.D3DCommon.hpp>	// (rtl)
#include <Winapi.D2D1.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <FMX.DialogService.Sync.hpp>	// (fmx)
#include <FMX.Dialogs.hpp>	// (fmx)
#include <FMX.DialogService.hpp>	// (fmx)
#include <FMX.Menus.hpp>	// (fmx)
#include <Winapi.Imm.hpp>	// (rtl)
#include <Winapi.MsCTF.PkgHelper.hpp>	// (rtl)
#include <System.Win.ComConst.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Winapi.ShellScaling.hpp>	// (rtl)
#include <FMX.Helpers.Win.hpp>	// (fmx)
#include <FMX.FontGlyphs.Win.hpp>	// (fmx)
#include <FMX.FontGlyphs.hpp>	// (fmx)
#include <FMX.Objects.hpp>	// (fmx)
#include <Winapi.TpcShrd.hpp>	// (rtl)
#include <Winapi.MsInkAut.hpp>	// (rtl)
#include <Winapi.Manipulations.hpp>	// (rtl)
#include <Winapi.RtsCom.hpp>	// (rtl)
#include <FMX.ZOrder.hpp>	// (fmx)
#include <FMX.ZOrder.Win.hpp>	// (fmx)
#include <System.IniFiles.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <Winapi.CommDlg.hpp>	// (rtl)
#include <Winapi.MMSystem.hpp>	// (rtl)
#include <FMX.MediaLibrary.hpp>	// (fmx)
#include <Winapi.WinSpool.hpp>	// (rtl)
#include <Winapi.DirectDraw.hpp>	// (rtl)
#include <Winapi.GDIPAPI.hpp>	// (rtl)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <Winapi.GDIPUTIL.hpp>	// (rtl)
#include <FMX.FontManager.hpp>	// (fmx)
#include <Winapi.D3D10.hpp>	// (rtl)
#include <Winapi.D3D10_1.hpp>	// (rtl)
#include <FMX.Canvas.D2D.hpp>	// (fmx)
#include <FMX.FontManager.Win.hpp>	// (fmx)
#include <FMX.Canvas.GDIP.hpp>	// (fmx)
#include <FMX.Printer.Win.hpp>	// (fmx)
#include <FMX.Printer.hpp>	// (fmx)
#include <FMX.StdActns.hpp>	// (fmx)
#include <FMX.Presentation.Messages.hpp>	// (fmx)
#include <FMX.Controls.Model.hpp>	// (fmx)
#include <FMX.Presentation.Factory.hpp>	// (fmx)
#include <FMX.Presentation.Style.hpp>	// (fmx)
#include <FMX.Controls.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.hpp>	// (fmx)
#include <FMX.Presentation.Style.Common.hpp>	// (fmx)
#include <FMX.Presentation.Win.Style.hpp>	// (fmx)
#include <FMX.Controls.Presentation.hpp>	// (fmx)
#include <FMX.Styles.Objects.hpp>	// (fmx)
#include <FMX.Styles.Switch.hpp>	// (fmx)
#include <FMX.Switch.Style.hpp>	// (fmx)
#include <FMX.Platform.Metrics.hpp>	// (fmx)
#include <FMX.Switch.Win.hpp>	// (fmx)
#include <FMX.StdCtrls.hpp>	// (fmx)
#include <FMX.InertialMovement.hpp>	// (fmx)
#include <FMX.Layouts.hpp>	// (fmx)
#include <FMX.Clipboard.Win.hpp>	// (fmx)
#include <FMX.Clipboard.hpp>	// (fmx)
#include <FMX.Text.UndoManager.hpp>	// (fmx)
#include <FMX.ScrollBox.Win.hpp>	// (fmx)
#include <FMX.ScrollBox.hpp>	// (fmx)
#include <FMX.ScrollBox.Style.hpp>	// (fmx)
#include <FMX.Text.LinesLayout.hpp>	// (fmx)
#include <FMX.Text.SelectionController.hpp>	// (fmx)
#include <FMX.Text.AutoscrollController.hpp>	// (fmx)
#include <FMX.SpellChecker.hpp>	// (fmx)
#include <FMX.Text.SpellingManager.hpp>	// (fmx)
#include <FMX.Text.IMERender.hpp>	// (fmx)
#include <FMX.Text.TextEditor.hpp>	// (fmx)
#include <FMX.MagnifierGlass.hpp>	// (fmx)
#include <FMX.Text.InteractiveSelectors.hpp>	// (fmx)
#include <FMX.Edit.Style.New.hpp>	// (fmx)
#include <FMX.Edit.Win.hpp>	// (fmx)
#include <FMX.Edit.hpp>	// (fmx)
#include <FMX.Dialogs.Default.hpp>	// (fmx)
#include <FMX.DialogHelper.hpp>	// (fmx)
#include <FMX.Dialogs.Win.hpp>	// (fmx)
#include <Winapi.Direct3D9.hpp>	// (rtl)
#include <FMX.Materials.Canvas.hpp>	// (fmx)
#include <FMX.Canvas.GPU.Helpers.hpp>	// (fmx)
#include <FMX.TextLayout.GPU.hpp>	// (fmx)
#include <FMX.StrokeBuilder.hpp>	// (fmx)
#include <FMX.Canvas.GPU.hpp>	// (fmx)
#include <FMX.Context.DX9.hpp>	// (fmx)
#include <Winapi.D3D11.hpp>	// (rtl)
#include <FMX.Context.DX11.hpp>	// (fmx)
#include <FMX.Forms.Border.hpp>	// (fmx)
#include <FMX.Forms.Border.Win.hpp>	// (fmx)
#include <FMX.MultiTouch.hpp>	// (fmx)
#include <FMX.MultiTouch.Win.hpp>	// (fmx)
#include <System.Win.StdVCL.hpp>	// (rtl)
#include <System.Win.OleControls.hpp>	// (rtl)
#include <System.Win.OleServers.hpp>	// (rtl)
#include <System.Win.InternetExplorer.hpp>	// (rtl)
#include <System.Win.IEInterfaces.hpp>	// (rtl)
#include <Winapi.WebView2.hpp>	// (rtl)
#include <Winapi.EdgeUtils.hpp>	// (rtl)
#include <FMX.Controls.Ole.hpp>	// (fmx)
#include <FMX.WebBrowser.Win.hpp>	// (fmx)
#include <FMX.WebBrowser.hpp>	// (fmx)
#include <FMX.KeyMapping.hpp>	// (fmx)
#include <FMX.AcceleratorKey.Win.hpp>	// (fmx)
#include <FMX.Platform.Screen.Win.hpp>	// (fmx)
#include <FMX.Platform.SaveState.Win.hpp>	// (fmx)
#include <FMX.Platform.Device.Win.hpp>	// (fmx)
#include <FMX.Platform.Metrics.Win.hpp>	// (fmx)
#include <FMX.ListBox.Selection.hpp>	// (fmx)
#include <FMX.ListBox.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.Types.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.hpp>	// (fmx)
#include <FMX.ExtCtrls.hpp>	// (fmx)
#include <FMX.Calendar.Style.hpp>	// (fmx)
#include <FMX.Calendar.hpp>	// (fmx)
#include <FMX.Pickers.Default.hpp>	// (fmx)
#include <FMX.Pickers.hpp>	// (fmx)
#include <FMX.VirtualKeyboard.Win.hpp>	// (fmx)
#include <FMX.Platform.Timer.Win.hpp>	// (fmx)
#include <FMX.Platform.Logger.Win.hpp>	// (fmx)
#include <FMX.Platform.Menu.Win.hpp>	// (fmx)
#include <FMX.Platform.Win.hpp>	// (fmx)
#include <FMX.Gestures.Win.hpp>	// (fmx)
#include <FMX.Gestures.hpp>	// (fmx)
#include <FMX.Controls.hpp>	// (fmx)
#include <FMX.Header.hpp>	// (fmx)
#include <FMX.Forms.hpp>	// (fmx)
#include <FMX.Platform.Common.hpp>	// (fmx)
#include <FMX.Platform.hpp>	// (fmx)
#include <FMX.ActnList.hpp>	// (fmx)
#include <FMX.Types.hpp>	// (fmx)
#include <FMX.Graphics.hpp>	// (fmx)
#include <Stage.OpenGLTokens.hpp>	// (GXScene_RT)
#include <Stage.TextureFormat.hpp>	// (GXScene_RT)
#include <Stage.Utils.hpp>	// (GXScene_RT)
#include <Stage.Logger.hpp>	// (GXScene_RT)
#include <Stage.PipelineTransform.hpp>	// (GXScene_RT)
#include <GXS.Coordinates.hpp>	// (GXScene_RT)
#include <GXS.Color.hpp>	// (GXScene_RT)
#include <GXS.XOpenGL.hpp>	// (GXScene_RT)
#include <GXS.ApplicationFileIO.hpp>	// (GXScene_RT)
#include <GXS.State.hpp>	// (GXScene_RT)
#include <GXS.Context.hpp>	// (GXScene_RT)
#include <GXS.Silhouette.hpp>	// (GXScene_RT)
#include <Stage.OpenGL4.hpp>	// (GXScene_RT)
#include <GXS.ImageUtils.hpp>	// (GXScene_RT)
#include <GXS.Graphics.hpp>	// (GXScene_RT)
#include <GXS.RenderContextInfo.hpp>	// (GXScene_RT)
#include <GXS.PictureRegisteredFormats.hpp>	// (GXScene_RT)
#include <GXS.Texture.hpp>	// (GXScene_RT)
#include <GXS.Material.hpp>	// (GXScene_RT)
#include <GXS.Selection.hpp>	// (GXScene_RT)
#include <GXS.Scene.hpp>	// (GXScene_RT)
#include <Stage.Spline.hpp>	// (GXScene_RT)
#include <GXS.Nodes.hpp>	// (GXScene_RT)
#include <GXS.Objects.hpp>	// (GXScene_RT)
#include <Stage.Polynomials.hpp>	// (GXScene_RT)
#include <GXS.Mesh.hpp>	// (GXScene_RT)
#include <GXS.Octree.hpp>	// (GXScene_RT)
#include <GXS.MeshUtils.hpp>	// (GXScene_RT)
#include <GXS.BaseMeshSilhouette.hpp>	// (GXScene_RT)
#include <GXS.VectorFileObjects.hpp>	// (GXScene_RT)
#include <GXS.GeomObjects.hpp>	// (GXScene_RT)
#include <GXS.HeightData.hpp>	// (GXScene_RT)
#include <Stage.VectorTypesExt.hpp>	// (GXScene_RT)
#include <GXS.MultiPolygon.hpp>	// (GXScene_RT)
#include <GXS.SpaceText.hpp>	// (GXScene_RT)
#include <GXS.Isolines.hpp>	// (GXScene_RT)
#include <GXS.ROAMPatch.hpp>	// (GXScene_RT)
#include <GXS.TerrainRenderer.hpp>	// (GXScene_RT)
#include <GXS.Graph.hpp>	// (GXScene_RT)
#include <GXS.SpacePartition.hpp>	// (GXScene_RT)
#include <GXS.VerletTypes.hpp>	// (GXScene_RT)
#include <GXS.VerletClothify.hpp>	// (GXScene_RT)
#include <GXS.Ragdoll.hpp>	// (GXScene_RT)
#include <GXS.Behaviours.hpp>	// (GXScene_RT)
// PRG_EXT: .bpl
// BPI_DIR: ..\lib\Win64
// OBJ_DIR: ..\lib\Win64
// OBJ_EXT: .o

//-- user supplied -----------------------------------------------------------

namespace Gxscene_physics_rt
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Gxscene_physics_rt */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GXSCENE_PHYSICS_RT)
using namespace Gxscene_physics_rt;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// GXScene_Physics_RTHPP
