// CodeGear C++Builder
// Copyright (c) 1995, 2024 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'GXS.InitOpenGL.pas' rev: 36.00 (Windows)

#ifndef GXS_InitOpenGLHPP
#define GXS_InitOpenGLHPP

#pragma delphiheader begin
#pragma option push
#if defined(__BORLANDC__) && !defined(__clang__)
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#endif
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>
#include <Winapi.OpenGL.hpp>
#include <Winapi.OpenGLext.hpp>
#include <Winapi.Windows.hpp>
#include <FMX.Forms.hpp>

//-- user supplied -----------------------------------------------------------

namespace Gxs
{
namespace Initopengl
{
//-- forward type declarations -----------------------------------------------
class DELPHICLASS TgxOpenGL;
class DELPHICLASS TgxShader;
class DELPHICLASS TgxShaderV;
class DELPHICLASS TgxShaderG;
class DELPHICLASS TgxShaderF;
class DELPHICLASS TgxProgram;
template<typename _TYPE_> class DELPHICLASS TgxBuffer__1;
template<typename _TYPE_> class DELPHICLASS TgxBufferV__1;
template<typename _TYPE_> class DELPHICLASS TgxBufferI__1;
template<typename _TYPE_> class DELPHICLASS TgxBufferU__1;
class DELPHICLASS TgxArray;
//-- type declarations -------------------------------------------------------
#pragma pack(push,4)
class PASCALIMPLEMENTATION TgxOpenGL : public System::TObject
{
	typedef System::TObject inherited;
	
private:
	Fmx::Forms::TCommonCustomForm* CommonCustomForm;
	HWND _WND;
	HDC _DC;
	
protected:
	Winapi::Windows::TPixelFormatDescriptor _PFD;
	int _PFI;
	HGLRC _RC;
	void __fastcall SetPFD(const Winapi::Windows::TPixelFormatDescriptor &PFD_);
	void __fastcall SetPFI(const int PFI_);
	void __fastcall CreateWindow();
	void __fastcall DestroyWindow();
	void __fastcall ValidatePFD(const Winapi::Windows::TPixelFormatDescriptor &PFD_);
	void __fastcall ValidatePFI(const int PFI_);
	void __fastcall CreateDC();
	void __fastcall DestroyDC();
	void __fastcall CreateRC();
	void __fastcall DestroyRC();
	
public:
	__fastcall TgxOpenGL();
	__fastcall virtual ~TgxOpenGL();
	__property Winapi::Windows::TPixelFormatDescriptor PFD = {read=_PFD, write=SetPFD};
	__property int PFI = {read=_PFI, write=SetPFI, nodefault};
	__property HGLRC RC = {read=_RC, nodefault};
	__classmethod Winapi::Windows::TPixelFormatDescriptor __fastcall DefaultPFD();
	void __fastcall BeginGL();
	void __fastcall EndGL();
	void __fastcall InitOpenGL();
	void __fastcall ApplyPixelFormat(const HDC DC_);
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION TgxShader : public System::TObject
{
	typedef System::TObject inherited;
	
protected:
	unsigned _ID;
	
public:
	__fastcall TgxShader(const unsigned Kind_);
	__fastcall virtual ~TgxShader();
	__property unsigned ID = {read=_ID, nodefault};
	void __fastcall SetSource(const System::UnicodeString Source_);
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION TgxShaderV : public TgxShader
{
	typedef TgxShader inherited;
	
public:
	__fastcall TgxShaderV();
	__fastcall virtual ~TgxShaderV();
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION TgxShaderG : public TgxShader
{
	typedef TgxShader inherited;
	
public:
	__fastcall TgxShaderG();
	__fastcall virtual ~TgxShaderG();
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION TgxShaderF : public TgxShader
{
	typedef TgxShader inherited;
	
public:
	__fastcall TgxShaderF();
	__fastcall virtual ~TgxShaderF();
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION TgxProgram : public System::TObject
{
	typedef System::TObject inherited;
	
protected:
	unsigned _ID;
	
public:
	__fastcall TgxProgram();
	__fastcall virtual ~TgxProgram();
	void __fastcall Attach(TgxShader* const Shader_);
	void __fastcall Detach(TgxShader* const Shader_);
	void __fastcall Link();
	void __fastcall Use();
};

#pragma pack(pop)

#pragma pack(push,4)
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename _TYPE_> class PASCALIMPLEMENTATION TgxBuffer__1 : public System::TObject
{
	typedef System::TObject inherited;
	
	
public:
	typedef _TYPE_ *_PValue_;
	
	
protected:
	unsigned _ID;
	unsigned _Kind;
	int _Count;
	_PValue_ _Head;
	void __fastcall SetCount(const int Count_);
	
public:
	__fastcall TgxBuffer__1(const unsigned Kind_);
	__fastcall virtual ~TgxBuffer__1();
	__property unsigned ID = {read=_ID, nodefault};
	__property int Count = {read=_Count, write=SetCount, nodefault};
	void __fastcall Bind();
	void __fastcall Unbind();
	void __fastcall Map();
	void __fastcall Unmap();
};

#pragma pack(pop)

#pragma pack(push,4)
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename _TYPE_> class PASCALIMPLEMENTATION TgxBufferV__1 : public TgxBuffer__1<_TYPE_>
{
	typedef TgxBuffer__1<_TYPE_> inherited;
	
public:
	__fastcall TgxBufferV__1();
	__fastcall virtual ~TgxBufferV__1();
};

#pragma pack(pop)

#pragma pack(push,4)
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename _TYPE_> class PASCALIMPLEMENTATION TgxBufferI__1 : public TgxBuffer__1<_TYPE_>
{
	typedef TgxBuffer__1<_TYPE_> inherited;
	
public:
	__fastcall TgxBufferI__1();
	__fastcall virtual ~TgxBufferI__1();
};

#pragma pack(pop)

#pragma pack(push,4)
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename _TYPE_> class PASCALIMPLEMENTATION TgxBufferU__1 : public TgxBuffer__1<_TYPE_>
{
	typedef TgxBuffer__1<_TYPE_> inherited;
	
public:
	__fastcall TgxBufferU__1();
	__fastcall virtual ~TgxBufferU__1();
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION TgxArray : public System::TObject
{
	typedef System::TObject inherited;
	
protected:
	unsigned _ID;
	
public:
	__fastcall TgxArray();
	__fastcall virtual ~TgxArray();
	__property unsigned ID = {read=_ID, nodefault};
	void __fastcall BeginBind();
	void __fastcall EndBind();
};

#pragma pack(pop)

//-- var, const, procedure ---------------------------------------------------
extern DELPHI_PACKAGE TgxOpenGL* GXOpenGL;
}	/* namespace Initopengl */
}	/* namespace Gxs */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GXS_INITOPENGL)
using namespace Gxs::Initopengl;
#endif
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GXS)
using namespace Gxs;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// GXS_InitOpenGLHPP
